function [n, C, w] = BPPrandomInstance(C, n, w_min, w_max)
arguments
    C = 1000
    n = 200
    w_min = 0.2*C
    w_max = 0.7*C
end
%Random instance generated by the BPP paper
% n \in {50, 100, 200, 300, 400, 500, 750, 1000}
% c \in {50, 75, 100, 120, 125, 150, 200, 300, 400, 500, 750, 1000}
% w_min \in {0.1c, 0.2c}
% w_max \in {0.7c, 0.8c}
% random weights in [w_min, w_max]
% the value are shadow weights from an LP?????
w = randi(w_max-w_min, 1, n) + w_min;